apiVersion: v1
data:
  servers.json: |-
    {
        "Servers": {
            "1": {
                "Name": "spend-api-db",
                "Group": "Servers",
                "Port": 5432,
                "Username": "spend_api_user",
                "Host": "spend-api-db.default.svc.cluster.local",
                "SSLMode": "prefer",
                "MaintenanceDB": "postgres",
                "PassFile": "/pgadmin4/pgpass"
            }
        }
    }
  pgpass: |-
    spend-api-db.default.svc.cluster.local:5432:postgres:spend_api_user:password

kind: ConfigMap
metadata:
  name: server-definition
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spend-api-db-admin
  labels:
    app: spend-api-db-admin
spec:
  selector:
    matchLabels:
      app: spend-api-db-admin
  template:
    metadata:
      labels:
        app: spend-api-db-admin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: password
        volumeMounts:
          - name: server-definition
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
          - name: server-definition
            mountPath: /pgadmin4/pgpass
            subPath: pgpass
      volumes:
        - name: server-definition
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: server-definition