apiVersion: v1
kind: Service
metadata:
  name: spend-api-db
spec:
  type: NodePort
  selector:
    app: spend-api-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spend-api-db
  labels:
    app: spend-api-db
spec:
  selector:
    matchLabels:
      app: spend-api-db
  template:
    metadata:
      labels:
        app: spend-api-db
    spec:
      containers:
      - name: postgres
        image: postgres:13.4-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: spend_api_db
        - name: POSTGRES_USER
          value: spend_api_user
        - name: POSTGRES_PASSWORD
          value: password